import io
import os
import re
from pypinyin import pinyin, Style

INPUT_FILES = [
    r"C:\Users\Utente\Documents\Jan\SW\Wangruanyin\pinyin_local_dict_part1.js",
    r"C:\Users\Utente\Documents\Jan\SW\Wangruanyin\pinyin_local_dict_part2.js",
]
OUTPUT_FILE = r"C:\Users\Utente\Documents\Jan\SW\Wangruanyin\pinyin-dict-characters.js"

ENTRY_RE = re.compile(r'LOCAL_PINYIN_DICT\["([^"]+)"\]\s*=\s*(\[[^\]]+\]);')


def is_cjk_char(ch):
    cp = ord(ch)
    return (
        0x3400 <= cp <= 0x4DBF or
        0x4E00 <= cp <= 0x9FFF or
        0xF900 <= cp <= 0xFAFF or
        0x20000 <= cp <= 0x2A6DF or
        0x2F800 <= cp <= 0x2FA1F
    )


def extract_entries_from_js(filepath):
    entries = {}
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            match = ENTRY_RE.search(line)
            if match:
                word = match.group(1)
                pinyin_list = match.group(2)
                entries[word] = pinyin_list
    return entries


def split_all_characters(all_entries):
    lines = []
    for word, pinyin_list in all_entries.items():
        try:
            values = eval(pinyin_list)
        except Exception:
            values = None
        if not isinstance(values, list) or not values:
            continue
        chars = list(word)
        for i, char in enumerate(chars):
            if not is_cjk_char(char):
                continue
            py = None
            if i < len(values):
                py = values[i]
            else:
                py = values[0]
            if not py:
                continue
            lines.append((char, [py]))
    return lines


def generate_complete_coverage(lines):
    """
    Ensure COMPLETE coverage: also generate pinyin via pypinyin for the full
    CJK Unified Ideographs block, so simplified AND traditional characters are
    covered even if they never appeared in the source dictionaries.

    Returns a dict char -> [pinyin] (first reading only).
    """
    result = {}
    for char, py_list in lines:
        if char not in result:
            result[char] = py_list

    added = 0
    for cp in range(0x4E00, 0x9FFF + 1):
        ch = chr(cp)
        if ch in result:
            continue
        try:
            py = pinyin(ch, style=Style.TONE)[0][0]
        except Exception:
            continue
        # pypinyin returns the char itself when it does not know it
        if not py or py == ch:
            continue
        result[ch] = [py]
        added += 1

    print("Characters added from pypinyin full-CJK coverage:", added)
    return result


def write_character_dict(filepath, char_dict):
    with open(filepath, "w", encoding="utf-8") as out:
        out.write("// pinyin-dict-characters.js\n")
        out.write("// Pinyin dict - character level (1 char = 1 pinyin)\n")
        out.write("// All source splits + pypinyin full-CJK coverage (simplified + traditional)\n")
        out.write("// Generated by fix_pinyin_dict.py\n\n")
        out.write('var LOCAL_PINYIN_DICT = typeof LOCAL_PINYIN_DICT !== "undefined" ? LOCAL_PINYIN_DICT : {};\n\n')

        for char in sorted(char_dict.keys()):
            pinyin_list = char_dict[char]
            out.write('LOCAL_PINYIN_DICT["{0}"] = {1};\n'.format(char, pinyin_list))


def main():
    print("=== Complete Pinyin Dictionary Generator ===")
    for f in INPUT_FILES:
        print("Input: {0}".format(f))
    print("Output: {0}".format(OUTPUT_FILE))
    print("---------------------------------------")

    all_entries = {}
    for f in INPUT_FILES:
        print("Reading {0}...".format(os.path.basename(f)))
        entries = extract_entries_from_js(f)
        all_entries.update(entries)
        print("  -> {0} entries (total: {1})".format(len(entries), len(all_entries)))
    print("Total word entries: {0}".format(len(all_entries)))

    print("Splitting ALL words into single-character lines...")
    lines = split_all_characters(all_entries)
    print("Character lines from split: {0}".format(len(lines)))

    print("Generating complete CJK coverage with pypinyin...")
    result = generate_complete_coverage(lines)
    print("Final unique characters: {0}".format(len(result)))

    print("Writing dictionary...")
    write_character_dict(OUTPUT_FILE, result)

    print("---------------------------------------")
    print("File generated: {0}".format(OUTPUT_FILE))
    print("Final character entries: {0}".format(len(result)))
    print("Done!")
    print("---------------------------------------")


if __name__ == "__main__":
    main()